services:
  clean_runners:
    image: ghcr.io/wjentner/gitlab-runner-cleaner:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '~/.kube/config:/root/.kube/config'
    # environment:
      # GRC_NAMESPACE: '<GITLAB RUNNER NAMESPACE>'
      # GRC_CONTEXT: '<KUBERNETES CONTEXT>'
      # GRC_HOUR_THRESHOLD: 1.5
      # GRC_RESOURCE_PREFIX: 'runner-'
      # GRC_RESOURCES: 'pod,secret,configmap'
      # GRC_NUM_RETRIES: 10
