name: Build and push latest image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Registry login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build image
      run: docker build . --file Dockerfile --tag ghcr.io/wjentner/gitlab-runner-cleaner:latest

    - name: Push image
      run: docker push ghcr.io/wjentner/gitlab-runner-cleaner:latest
